### ISSUE TITLE
Problems extracting frame from mp4 video

### ISSUE THREAD

**Issue by migore** [jcodec/jcodec#66] opened 2015-01-19 20:59 UTC
I tried with org.jcodec.api.android.FrameGrab and with org.jcodec.api.FrameGrab. I get the same exception in both cases in the following line of code.:
FrameGrab.getNativeFrame(new File("videoFile"), i);

This is the exception that I get:

can't instantiate class org.jcodec.containers.mp4.boxes.UrlBox; no empty constructor
at org.jcodec.containers.mp4.boxes.NodeBox.newBox(NodeBox.java:70)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:75)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.DataRefBox.parse(DataRefBox.java:35)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
at org.jcodec.containers.mp4.MP4Util$Atom.parseBox(MP4Util.java:98)
at org.jcodec.containers.mp4.MP4Util.parseMovie(MP4Util.java:56)
at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:58)
at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:50)
at org.jcodec.api.FrameGrab.<init>(FrameGrab.java:75)
at org.jcodec.api.FrameGrab.getNativeFrame(FrameGrab.java:277)

The file is there and. Am I passing a wrong parameter? I tried version 0.1.5 (the one here), 0.1.7 (downloaded from jcodec.org) and 0.1.9 from maven central.

I'm using Output format: MediaRecorder.OutputFormat.MPEG_4 and Video encoder: MediaRecorder.VideoEncoder.H264.

**Comment by gcgrant** [comment] 2015-07-27 21:32
Running into a very similar problem. Ever find a resolution?

    Caused by: java.lang.RuntimeException: java.lang.InstantiationException: class org.jcodec.containers.mp4.boxes.UrlBox has no zero argument constructor
            at org.jcodec.containers.mp4.boxes.NodeBox.newBox(NodeBox.java:70)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:75)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.DataRefBox.parse(DataRefBox.java:35)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseChildBox(NodeBox.java:54)
            at org.jcodec.containers.mp4.boxes.NodeBox.parse(NodeBox.java:39)
            at org.jcodec.containers.mp4.boxes.NodeBox.parseBox(NodeBox.java:78)
            at org.jcodec.containers.mp4.MP4Util$Atom.parseBox(MP4Util.java:98)
            at org.jcodec.containers.mp4.MP4Util.parseMovie(MP4Util.java:56)
            at org.jcodec.containers.mp4.demuxer.MP4Demuxer.findMovieBox(MP4Demuxer.java:58)
            at org.jcodec.containers.mp4.demuxer.MP4Demuxer.<init>(MP4Demuxer.java:50)
            at org.jcodec.api.FrameGrab.<init>(FrameGrab.java:75)
            at org.jcodec.api.android.FrameGrab.<init>(FrameGrab.java:40)

**Comment by svitvitskiy** [comment] 2015-07-27 22:14
Fixed in 7efdc640791836affea5d54501eeffdcb768c510

**Closed by svitvitskiy** 2015-07-27 22:14 UTC
